version: '3.8'

services:
  php:
    build: .
    user: "${UID:-1000}:${GID:-1000}"
    restart: on-failure
    volumes:
      - .:/var/www
    environment:
      TZ: UTC
      YII_ENV: dev
      YII_DEBUG: "true"
    depends_on:
      - mariadb
    env_file: .env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mariadb:
    image: mariadb:11.7-rc
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: yii2
      MARIADB_USER: yii2
      MARIADB_PASSWORD: yii2
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mariadb_data:
